version: 2

sources:
  - name: staging
    database: terraform-demo-428522 # Se carga el nombre de BigQuery donde tenemos los datasets
     # For postgres:
      #database: production
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}

